In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split,KFold
from sklearn.linear_model import LinearRegression , Ridge , Lasso
from sklearn import metrics
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures

In [2]:
df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
df['mainroad'] = df['mainroad'].map({'yes': 1, 'no': 0})
df['guestroom'] = df['guestroom'].map({'yes': 1, 'no': 0})
df['basement'] = df['basement'].map({'yes': 1, 'no': 0})
df['hotwaterheating'] = df['hotwaterheating'].map({'yes': 1, 'no': 0})
df['airconditioning'] = df['airconditioning'].map({'yes': 1, 'no': 0})
df['prefarea'] = df['prefarea'].map({'yes': 1, 'no': 0})
df['furnishingstatus'] = df['furnishingstatus'].map({'furnished':2, 'semi-furnished': 1, 'unfurnished': 0})

In [4]:
df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,2
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,2
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,2
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,2
5,10850000,7500,3,3,1,1,0,1,0,1,2,1,1
6,10150000,8580,4,3,4,1,0,0,0,1,2,1,1
7,10150000,16200,5,3,2,1,0,0,0,0,0,0,0
8,9870000,8100,4,1,2,1,1,1,0,1,2,1,2
9,9800000,5750,3,2,4,1,1,0,0,1,1,1,0

##Define output

In [ ]:
# Y = df['price']

#1. Simple Linear Regression (Single Feature)

In [35]:
# # Use only ONE feature
# X = df[['area']]

# # Split
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# # Model
# model = LinearRegression()
# model.fit(X_train, Y_train)

# # Prediction
# Y_pred = model.predict(X_test)

# # Evaluation
# print("Simple Linear Regression")
# print("MSE:", mean_squared_error(Y_test, Y_pred))
# print("R2 Score:", r2_score(Y_test, Y_pred))

In [ ]:
# from sklearn.model_selection import KFold, cross_val_score
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error, r2_score
# import numpy as np

# # Use only ONE feature
# X = df[['area']]
# Y = df['price']   # target column

# # Model
# model = LinearRegression()

# # K-Fold Cross Validation
# kf = KFold(n_splits=5, shuffle=True, random_state=42)

# # R2 scores for each fold
# r2_scores = cross_val_score(model, X, Y, cv=kf, scoring='r2')

# # MSE scores for each fold
# mse_scores = cross_val_score(
#     model,
#     X,
#     Y,
#     cv=kf,
#     scoring='neg_mean_squared_error'
# )

# # Convert negative MSE to positive
# mse_scores = -mse_scores

# # Print Results
# print("Simple Linear Regression using K-Fold Cross Validation")
# print("R2 Scores for each fold:", r2_scores)
# print("Average R2 Score:", np.mean(r2_scores))

# print("MSE for each fold:", mse_scores)
# print("Average MSE:", np.mean(mse_scores))

Simple Linear Regression using K-Fold Cross Validation
R2 Scores for each fold: [ 0.27287852  0.25974785 -0.05741414  0.33879088  0.31720979]
Average R2 Score: 0.22624257978867965
MSE for each fold: [3.67528660e+12 3.13010635e+12 1.69744445e+12 1.84987474e+12
 2.39796206e+12]
Average MSE: 2550134840966.046

#multiple regression

In [36]:
# # Define features and target
# X = df.drop('price', axis=1)   # assuming 'price' is target
# y = df['price']

# # Split
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# model_multi = LinearRegression()
# model_multi.fit(X_train, Y_train)

# y_pred_m = model_multi.predict(X_test)

# print("\nMultiple Linear Regression")
# print("MSE:", mean_squared_error(Y_test, y_pred_m))
# print("R2 Score:", r2_score(Y_test, y_pred_m))

In [ ]:
# from sklearn.model_selection import KFold, cross_val_score
# from sklearn.linear_model import LinearRegression
# import numpy as np

# # Define features and target
# X = df.drop('price', axis=1)   # Features
# Y = df['price']                # Target

# # Model
# model_multi = LinearRegression()

# # K-Fold Cross Validation
# kf = KFold(n_splits=5, shuffle=True, random_state=42)

# # R2 Scores
# r2_scores = cross_val_score(
#     model_multi,
#     X,
#     Y,
#     cv=kf,
#     scoring='r2'
# )

# # MSE Scores
# mse_scores = -cross_val_score(
#     model_multi,
#     X,
#     Y,
#     cv=kf,
#     scoring='neg_mean_squared_error'
# )

# # RMSE Scores
# rmse_scores = np.sqrt(mse_scores)

# # Print Results
# print("Multiple Linear Regression using K-Fold Cross Validation")

# print("R2 Scores for each fold:", r2_scores)
# print("Average R2 Score:", np.mean(r2_scores))

# print("\nMSE for each fold:", mse_scores)
# print("Average MSE:", np.mean(mse_scores))

# print("\nRMSE for each fold:", rmse_scores)
# print("Average RMSE:", np.mean(rmse_scores))

Multiple Linear Regression using K-Fold Cross Validation
R2 Scores for each fold: [0.64947542 0.7119651  0.49359487 0.65835448 0.64591794]
Average R2 Score: 0.6318615631007681

MSE for each fold: [1.77175112e+12 1.21793615e+12 8.12921400e+11 9.55826825e+11
 1.24353766e+12]
Average MSE: 1200394629952.1382

RMSE for each fold: [1331071.41678951 1103601.44530071  901621.53917865  977663.96337939
 1115140.19652027]
Average RMSE: 1085819.712233706

## Polynomial Regression

In [37]:
# # Step 1: Create polynomial features
# # Define features and target
# X = df.drop('price', axis=1)   # assuming 'price' is target
# Y = df['price']

# # Split
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# poly = PolynomialFeatures(degree=2)

# X_train_poly = poly.fit_transform(X_train)
# X_test_poly = poly.transform(X_test)

# # Step 2: Scale data
# scaler = StandardScaler()

# X_train_poly_scaled = scaler.fit_transform(X_train_poly)
# X_test_poly_scaled = scaler.transform(X_test_poly)

# # Step 3: Train model
# model_poly = LinearRegression()
# model_poly.fit(X_train_poly_scaled, Y_train)

# # Predict
# Y_pred_poly = model_poly.predict(X_test_poly_scaled)

# print("\nPolynomial Regression")
# print("MSE:", mean_squared_error(Y_test, Y_pred_poly))
# print("R2:", r2_score(Y_test, Y_pred_poly))

# 5. Ridge Regression

In [38]:
# X = df.drop('price', axis=1)   # assuming 'price' is target
# Y = df['price']

# # Split
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# # Scale data
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# # Train Ridge
# ridge_model = Ridge(alpha=1.0)
# ridge_model.fit(X_train_scaled, Y_train)

# Y_pred_ridge = ridge_model.predict(X_test_scaled)

# print("\nRidge Regression")
# print("MSE:", mean_squared_error(Y_test, Y_pred_ridge))
# print("R2:", r2_score(Y_test, Y_pred_ridge))

In [39]:
X = df.drop('price', axis=1)   # assuming 'price' is target
Y = df['price']

# Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
# Scale data (important for Lasso)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Lasso
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train_scaled, Y_train)

Y_pred_lasso = lasso_model.predict(X_test_scaled)

print("\nLasso Regression")
print("MSE:", mean_squared_error(Y_test, Y_pred_lasso))
print("R2:", r2_score(Y_test, Y_pred_lasso))

Lasso Regression
MSE: 1771751296940.0142
R2: 0.6494753835469955